version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  auth-api:
    extends:
      file: ./compose/compose.published.yml
      service: auth-api

  user-api:
    extends:
      file: ./compose/compose.published.yml
      service: user-api

  task-api:
    extends:
      file: ./compose/compose.published.yml
      service: task-api

  front:
    extends:
      file: ./compose/compose.published.yml
      service: front

networks:
  default:
    external: true
    name: grpc-task-manager_default
