---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    app: api
spec:
  ports:
    - name: grpc
      port: 4001
      targetPort: 4000
  selector:
    app: user-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-api
      annotations:
        autocert.step.sm/name: user-api.grpc-tm
    spec:
      containers:
        - image: mohammaddocker/tm-user-api
          name: user-api
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          volumeMounts:
            - name: tls
              mountPath: "/tls"
              readOnly: true
            - name: certs
              mountPath: "/certs"
              readOnly: true
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: api-map
                  key: USER_DB_URL
            - name: AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-map
                  key: AUTH_API_URL
      volumes:
      - name: tls
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-name: tm-selfsigned
            csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}
      - name: certs
        secret:
          secretName: user-api-cert-tls
          items:
            - key: tls.key
              path: certificate.key
            - key: tls.crt
              path: certificate.crt 
