name: Update generated stubs

on:
  # push:
  #   branches:
  #     - main
  #     - feat/**
  #   paths:
  #     - "proto/**.proto"
  #     - ".github/workflows/proto.yml"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0
      # Installs latest

      - uses: bufbuild/buf-setup-action@v1.12.0
        with:
          buf_user: bneiconseil
          buf_api_token: ${{ secrets.BUF_TOKEN }}

      - run: |
          cd proto
          buf generate

      - name: Update server stubs and proto
        run: |
          buf export buf.build/bneiconseil/taskmanagerapi -o ./task-api/src/proto
          buf export buf.build/bneiconseil/taskmanagerapi -o ./user-api/src/proto
          buf export buf.build/bneiconseil/taskmanagerapi -o ./auth-api/src/proto

      - name: Commit stubs
        run: |
          git config --local user.email "mohammadamine.banaei@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "feat(stubs): updated stubs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
